# import thư viện

In [1]:
import pandas_ta as ta
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_btc = pd.read_csv('/Users/dophi/Desktop/Crypto_dashboard_predict/eda/BTCUSDT_1d_cleaned.csv')
df_eth = pd.read_csv('/Users/dophi/Desktop/Crypto_dashboard_predict/eda/ETHUSDT_1d_cleaned.csv')

In [3]:
help(ta.rsi)

Help on function rsi in module pandas_ta.momentum.rsi:

rsi(close: pandas.core.series.Series, length: Union[int, numpy.integer] = None, scalar: Union[int, numpy.integer, float, numpy.floating] = None, mamode: str = None, talib: bool = None, drift: Union[int, numpy.integer] = None, offset: Union[int, numpy.integer] = None, **kwargs: Optional[dict]) -> pandas.core.series.Series
    Relative Strength Index

    This oscillator used to attempts to quantify "velocity" and "magnitude".

    Sources:
        * [tradingview](https://www.tradingview.com/wiki/Relative_Strength_Index_(RSI))

    Parameters:
        close (Series): ```close``` Series
        length (int): The period. Default: ```14```
        scalar (float): Scalar. Default: ```100```
        mamode (str): See ```help(ta.ma)```. Default: ```"rma"```
        talib (bool): If installed, use TA Lib. Default: ```True```
        drift (int): Difference amount. Default: ```1```
        offset (int): Post shift. Default: ```0```

    Other Parameters:
        fillna (value): ```pd.DataFrame.fillna(value)```

    Returns:
        (Series): 1 column

    Warning:
        TA-Lib Correlation: ```np.float64(0.9289853267851295)```

    Tip:
        Corrective contributions welcome!

# áp dụng chỉ số RSI vào dữ liệu

In [4]:
df_btc["rsi"] = ta.rsi(df_btc["close"], length = 14)
df_eth["rsi"] = ta.rsi(df_eth["close"], length = 14)

In [5]:
df_btc.head(15)

     open_time     open     high      low    close       volume        rsi
0   2017-08-17  4261.48  4485.39  4200.74  4285.08   795.150377        NaN
1   2017-08-18  4285.08  4371.52  3938.77  4108.37  1199.888264   0.000000
2   2017-08-19  4108.37  4184.69  3850.00  4139.98   381.309763   1.357328
3   2017-08-20  4120.98  4211.08  4032.62  4086.29   467.083022   1.324445
4   2017-08-21  4069.13  4119.62  3911.79  4016.00   691.743060   1.280701
5   2017-08-22  4016.00  4104.82  3400.00  4040.00   966.684858   2.465236
6   2017-08-23  4040.00  4265.80  4013.89  4114.01  1001.136565   6.202891
7   2017-08-24  4147.00  4371.68  4085.01  4316.01   787.418753  15.698458
8   2017-08-25  4316.01  4453.91  4247.48  4280.68   573.612740  15.404718
9   2017-08-26  4280.71  4367.00  4212.41  4337.44   228.108068  18.057478
10  2017-08-27  4332.51  4400.00  4285.54  4310.01   350.692585  17.767513
11  2017-08-28  4310.01  4399.82  4124.54  4386.69   603.841616  21.559532
12  2017-08-29  4353.65  4625.85  4313.55  4587.48   603.545028  30.586020
13  2017-08-30  4564.52  4647.51  4416.01  4555.14   808.468771  29.987469
14  2017-08-31  4555.14  4745.42  4555.14  4724.89   556.956802  36.960842

In [6]:
df_eth.head(15)

     open_time    open    high     low   close      volume        rsi
0   2017-08-17  301.13  312.18  298.00  302.00  7030.71034        NaN
1   2017-08-18  302.00  311.79  283.94  293.96  9537.84646   0.000000
2   2017-08-19  293.31  299.90  278.00  290.91  2146.19773   0.000000
3   2017-08-20  289.41  300.53  282.85  299.10  2510.13871   7.577971
4   2017-08-21  299.10  346.52  294.60  323.29  5219.44542  25.528580
5   2017-08-22  321.04  330.41  144.21  309.80  7956.35088  22.861868
6   2017-08-23  312.25  324.99  309.41  315.74  8665.72569  26.502536
7   2017-08-24  315.74  328.04  314.01  323.42  6753.27192  31.034664
8   2017-08-25  323.42  338.28  323.42  327.24  7125.96962  33.239795
9   2017-08-26  327.24  335.44  323.41  330.79  4877.68521  35.309894
10  2017-08-27  332.18  348.13  330.73  348.13  4635.43715  44.381750
11  2017-08-28  348.11  351.00  331.95  346.00  4279.18170  43.573408
12  2017-08-29  347.00  377.60  346.00  374.70  3032.13425  55.368880
13  2017-08-30  374.70  393.71  362.05  385.93  4446.59608  58.982047
14  2017-08-31  384.64  389.36  377.78  384.79  4435.86855  58.464616

- Khi tính chỉ báo RSI với chu kỳ n (thường là 14), các giá trị RSI ở những hàng đầu tiên luôn không ổn định và không phản ánh đúng động lượng thị trường.
- tính RSI bằng SMA thuần túy thì cần bỏ đúng n hàng (ví dụ 14 hàng). Còn khi dùng EMA như các thư viện hiện đại (pandas-ta, ta-lib, TradingView), RSI sẽ ổn định sớm hơn, nên chỉ cần loại bỏ khoảng 5–10 hàng đầu tiên.

# tính thay đổi phần trăm giá đóng cửa hàng ngày

In [7]:
df_btc['pct_change'] = df_btc['close'].pct_change() * 100
df_eth['pct_change'] = df_eth['close'].pct_change() * 100

In [8]:
df_btc.head(10)

,open_time,open,high,low,close,volume,rsi,pct_change
0,2017-08-17,4261.48,4485.39,4200.74,4285.08,795.150377,NaN,NaN
1,2017-08-18,4285.08,4371.52,3938.77,4108.37,1199.888264,0.000000,-4.123844
2,2017-08-19,4108.37,4184.69,3850.00,4139.98,381.309763,1.357328,0.769405
3,2017-08-20,4120.98,4211.08,4032.62,4086.29,467.083022,1.324445,-1.296866
4,2017-08-21,4069.13,4119.62,3911.79,4016.00,691.743060,1.280701,-1.720142
5,2017-08-22,4016.00,4104.82,3400.00,4040.00,966.684858,2.465236,0.597610
6,2017-08-23,4040.00,4265.80,4013.89,4114.01,1001.136565,6.202891,1.831931
7,2017-08-24,4147.00,4371.68,4085.01,4316.01,787.418753,15.698458,4.910051
8,2017-08-25,4316.01,4453.91,4247.48,4280.68,573.612740,15.404718,-0.818580
9,2017-08-26,4280.71,4367.00,4212.41,4337.44,228.108068,18.057478,1.325958

In [9]:
df_eth.head(10)

,open_time,open,high,low,close,volume,rsi,pct_change
0,2017-08-17,301.13,312.18,298.00,302.00,7030.71034,NaN,NaN
1,2017-08-18,302.00,311.79,283.94,293.96,9537.84646,0.000000,-2.662252
2,2017-08-19,293.31,299.90,278.00,290.91,2146.19773,0.000000,-1.037556
3,2017-08-20,289.41,300.53,282.85,299.10,2510.13871,7.577971,2.815304
4,2017-08-21,299.10,346.52,294.60,323.29,5219.44542,25.528580,8.087596
5,2017-08-22,321.04,330.41,144.21,309.80,7956.35088,22.861868,-4.172724
6,2017-08-23,312.25,324.99,309.41,315.74,8665.72569,26.502536,1.917366
7,2017-08-24,315.74,328.04,314.01,323.42,6753.27192,31.034664,2.432381
8,2017-08-25,323.42,338.28,323.42,327.24,7125.96962,33.239795,1.181127
9,2017-08-26,327.24,335.44,323.41,330.79,4877.68521,35.309894,1.084831

In [10]:
df_btc.describe()

,open,high,low,close,volume,rsi,pct_change
count,3046.000000,3046.000000,3046.000000,3046.000000,3046.000000,3045.000000,3045.000000
mean,35681.038628,36447.072905,34854.769921,35707.762209,62715.480976,52.185833,0.163455
std,31971.831924,32494.112971,31412.666042,31979.502266,76949.321675,13.976766,3.586611
min,3188.010000,3276.500000,2817.000000,3189.020000,228.108068,0.000000,-39.504847
25%,9138.775000,9307.572500,8853.700000,9141.367500,24604.920091,42.708693,-1.385361
50%,25955.990000,26350.460000,25625.105000,25994.290000,39835.196972,50.895101,0.070878
75%,54930.957500,57032.742500,53350.240000,54996.407500,65921.252732,61.360430,1.626145
max,124658.540000,126199.630000,123084.000000,124658.540000,760705.362783,93.453830,22.501393

In [11]:
df_eth.describe()

,open,high,low,close,volume,rsi,pct_change
count,3046.000000,3046.000000,3046.000000,3046.000000,3.046000e+03,3045.000000,3045.000000
mean,1639.454478,1687.153940,1586.407052,1640.284045,5.316573e+05,51.234566,0.181673
std,1298.125673,1332.664375,1259.516109,1298.088190,4.483534e+05,13.475941,4.619363
min,83.750000,85.000000,81.790000,83.760000,1.060567e+03,0.000000,-44.596886
25%,306.327500,318.000000,294.700000,307.725000,2.435931e+05,41.787034,-1.980262
50%,1608.485000,1650.025000,1562.175000,1610.315000,4.216592e+05,49.966626,0.070224
75%,2627.517500,2704.357500,2552.172500,2629.275000,6.935465e+05,60.326906,2.234614
max,4832.070000,4956.780000,4713.890000,4832.070000,4.663240e+06,89.791028,26.332887

In [12]:
df_btc = df_btc.iloc[14:].reset_index(drop=True)
df_eth = df_eth.iloc[14:].reset_index(drop=True)

In [13]:
df_btc

,open_time,open,high,low,close,volume,rsi,pct_change
0,2017-08-31,4555.14,4745.42,4555.14,4724.89,556.956802,36.960842,3.726559
1,2017-09-01,4689.89,4885.55,4654.88,4834.91,560.666366,41.058493,2.328520
2,2017-09-02,4796.16,4939.19,4286.87,4472.14,929.148595,33.358714,-7.503139
3,2017-09-03,4508.50,4714.76,4298.33,4509.08,691.216198,34.701566,0.826003
4,2017-09-04,4505.00,4527.49,3972.51,4100.11,1394.644614,27.979485,-9.069921
...,...,...,...,...,...,...,...,...
3027,2025-12-14,90240.00,90472.40,87577.36,88172.17,9416.940040,40.328830,-2.291489
3028,2025-12-15,88172.16,90052.64,85146.64,86432.08,19778.691900,37.114877,-1.973514
3029,2025-12-16,86432.08,88175.98,85266.00,87863.42,18456.050170,41.261572,1.656029
3030,2025-12-17,87863.43,90365.85,85314.00,86243.22,19834.117290,38.191612,-1.843998
3031,2025-12-18,86243.23,89477.61,84450.01,85516.41,25405.417630,36.866491,-0.842745

In [14]:
df_eth

,open_time,open,high,low,close,volume,rsi,pct_change
0,2017-08-31,384.64,389.36,377.78,384.79,4435.86855,58.464616,-0.295390
1,2017-09-01,386.44,394.39,383.18,388.46,4198.68434,59.690602,0.953767
2,2017-09-02,388.58,394.32,320.08,343.14,8240.32724,42.864777,-11.666581
3,2017-09-03,343.56,367.28,320.08,341.77,5253.62211,42.474997,-0.399254
4,2017-09-04,339.29,344.55,267.94,283.77,6737.81061,30.026532,-16.970477
...,...,...,...,...,...,...,...,...
3027,2025-12-14,3114.64,3129.54,3024.44,3063.50,279058.35450,46.391290,-1.641923
3028,2025-12-15,3063.49,3177.50,2894.57,2964.85,520509.95550,42.487142,-3.220173
3029,2025-12-16,2964.85,2981.87,2876.00,2962.30,378293.11590,42.387840,-0.086008
3030,2025-12-17,2962.30,3030.92,2791.02,2833.49,497630.41620,37.606415,-4.348310
3031,2025-12-18,2833.50,2997.40,2775.19,2828.57,595253.79970,37.432727,-0.173637

In [15]:
df_btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3032 entries, 0 to 3031
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   open_time   3032 non-null   object
 1   open        3032 non-null   float64
 2   high        3032 non-null   float64
 3   low         3032 non-null   float64
 4   close       3032 non-null   float64
 5   volume      3032 non-null   float64
 6   rsi         3032 non-null   float64
 7   pct_change  3032 non-null   float64
dtypes: float64(7), object(1)
memory usage: 189.6+ KB

In [16]:
df_eth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3032 entries, 0 to 3031
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   open_time   3032 non-null   object
 1   open        3032 non-null   float64
 2   high        3032 non-null   float64
 3   low         3032 non-null   float64
 4   close       3032 non-null   float64
 5   volume      3032 non-null   float64
 6   rsi         3032 non-null   float64
 7   pct_change  3032 non-null   float64
dtypes: float64(7), object(1)
memory usage: 189.6+ KB

In [17]:
df_btc.to_csv('/Users/dophi/Desktop/Crypto_dashboard_predict/feature_engineering/BTCUSDT_1d_fe.csv', index=False)
df_eth.to_csv('/Users/dophi/Desktop/Crypto_dashboard_predict/feature_engineering/ETHUSDT_1d_fe.csv', index=False)